### ISSUE TITLE
Doesn't remember API key

### ISSUE THREAD

**Issue by fetis** [vitaly-zdanevich/extension-firefox-yandex-translate#12]
Hi, I'm on Ubuntu 14.04. I entered API key, but after some I'm asked for it again. If I check preferences there's key. I can re-enter it and it starts working. So, it looks like addon doesn't send it for some reason

**Comment by vitaly-zdanevich** [comment]
Thank you, fixed in 1.7.9

But I have no time for testing, so I hope that now all is correct :)
