### ISSUE TITLE
setHotkeyFromPrefsForTranslatingAndReplacementSelectedText() exists twice

### ISSUE THREAD

**Issue by thenlich** [vitaly-zdanevich/extension-firefox-yandex-translate#15]
in index.js:147 and index.js:163
there are identical functions called setHotkeyFromPrefsForTranslatingAndReplacementSelectedText()

One is for backup?

**Comment by thenlich** [comment]
Also, the first line of this function
    if (hotkeyReplace) hotkey.destroy();
should probably read
    if (hotkeyReplace) hotkeyReplace.destroy();

**Comment by vitaly-zdanevich** [comment]
Thank you, I fixed this at 1.9.2
