### ISSUE TITLE
Changing of hotkeys not correctly working

### ISSUE THREAD

**Issue by thenlich** [vitaly-zdanevich/extension-firefox-yandex-translate#17]
1. Changing hotkey for popup (alt-Y) does not work immediately.
2. Changing hotkey for replace (accel-shift-T) also leaves the old hotkey active.

(At least until browser restart)

(Version 1.9.2, Firefox 43.0.1, Windows 7)
For example:
1. Changing hotkey alt-Y to alt-A: alt-Y is still working, alt-A not working
2. Changing hotkey accel-shift-T to accel-shift-A: both hotkeys are now active.

**Comment by vitaly-zdanevich** [comment]
Thank you for feedback, I fixed this at `1.9.3`
